# ddl-auto (create) : 개발 초기 환경에서 사용. 애플리케이션 로딩 시점에 모든 테이블을 drop 후 새로 생성, 애플리케이션 서버 종료 후에도 DB 보존
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/skillTradeMarket
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace